if (typeof ncbi === "undefined") {
    ncbi = {};
}

ncbi.sgAppsWithScrolling = [
    {"ncbi_app": "entrez",
     "ncbi_db": "gene",
     "ncbi_report": "full_report"},
     {"foo": "bar"}
];

;
(function(){function F(a){return ncbi.sg._urls.getAttrFromStr("jsevent",a)}function G(a){for(var b=ncbi.sg.reservedParams,c=0;c<b.length;c++)if(a==b[c])return true;return false}function H(a,b){b=ncbi.sg._urls.getDataObj(b);var c={},e=ncbi.sg.pingCallbacks;a=typeof e[a]!=="undefined"?e[a]:[];for(e=0;e<a.length;e++)ncbi.sg._urls.addDataToObj(c,a[e](b));for(var g in c)if(G(g)){delete c[g];console.warn("You tried to add param '"+g+"' to ping data, but that parameter is reserved.")}return c}if(typeof ncbi===
"undefined")ncbi={};if(ncbi.sg)typeof console!=="undefined"&&console.warn&&console.warn("The logging JavaScript was added twice in the document. Please include it once.");else{ncbi.sg=function(){};ncbi.sg.getInstance=function(){if(!ncbi.sg._instance)ncbi.sg._instance=new ncbi.sg;return ncbi.sg._instance};ncbi.sg._instance=null;ncbi.sg._version="33";(function(){var a=navigator.cookieEnabled?true:false;if(typeof navigator.cookieEnabled==="undefined"&&!a){document.cookie="testcookie";a=document.cookie.indexOf("testcookie")!==
-1?true:false}ncbi.sg.isCookieEnabled=a;ncbi.sg.isClickingEnabled=typeof __ncbi_sg_isClickingEnabled==="undefined"?true:!!__ncbi_sg_isClickingEnabled;ncbi.sg.calcXY=typeof __ncbi_sg_calcXY==="undefined"?true:!!__ncbi_sg_calcXY;a={};for(var b in window){var c=b.match(/^__ncbi_sg_pingCallbacks_(\w+)_(.+)$/);if(c&&typeof c[1]!=="undefined"){c=c[1];var e=window[b];a[c]=a[c]||[];a[c].push(e)}}ncbi.sg.pingCallbacks=a})();ncbi.sg.appLogIgnore=["ncbi_sessionid","ncbi_clickdisabled"];ncbi.sg.reservedParams=
["jsevent","sgSource","sgVersion","hasScrolled","jseventms","ncbi_phid","ncbi_timeonpage","ncbi_timesinceload"];ncbi.sg.prototype={init:function(){this.isProcessRunning=true;this._setUpMetaTagValues();this._setScrollingEnabled();if(this._cachedVals.ncbi_db&&this._cachedVals.ncbi_db.value.toLowerCase()=="pubmed"&&this._cachedVals.ncbi_report&&this._cachedVals.ncbi_report.value.toLowerCase()=="abstract"&&this._cachedVals.ncbi_resultcount&&this._cachedVals.ncbi_resultcount.value.toLowerCase()=="1"||
this._cachedVals.ncbi_db&&this._cachedVals.ncbi_db.value.toLowerCase()=="pmc"&&this._cachedVals.ncbi_report&&this._cachedVals.ncbi_report.value.toLowerCase()=="record"&&this._cachedVals.ncbi_type&&this._cachedVals.ncbi_type.value.toLowerCase()=="fulltext")ncbi.sg.isHoverEnabled=true;this._setUpPathParts();this._setUpCustomProps();this._addOnScrollListeners();this._send("init");this._scheduleDOMReadyPing();this._sendPrev();this._addPrintPing();ncbi.sg.isScrollingEnabled&&this._setBeforeScrollDetails()},
_vals:{},_cachedVals:{},_hasInitRun:false,_readyPinged:false,_linkObjs:[],_pathParts:{part1:"",part2:"",part3:"",part4:""},_scheduleDOMReadyPing:function(){var a=this,b=function(){return typeof jQuery!=="undefined"&&typeof jQuery.ui!=="undefined"&&typeof jQuery.ui.jig!=="undefined"?typeof jQuery.ui.jig.version!=="undefined"&&jQuery.ui.jig.version?jQuery.ui.jig.version:"unknown":"unknown"},c=function(){var n={},m=jQuery.ui.jig._foundWidgets;for(var u in m)n["jigWidget_"+u]=m[u];n.jigVersion=b();return n},
e=function(n){var m=ncbi.sg.getInstance();m.storeAllHeadings();for(var u=m.getVisibleHeadingIDs(),z=[],w=0;w<u.length;w++){var d=u[w];d&&z.push(encodeURIComponent(d))}m=m.getHiddenHeadingIDs();var f=[];for(w=0;w<m.length;w++)(d=m[w])&&f.push(encodeURIComponent(d));n["visible.headingIDs"]=z.join(",");n["numVisible.headingIDs"]=u.length;n["hidden.headingIDs"]=f.join(",");n["numHidden.headingIDs"]=m.length},g=function(){if(!a._readyPinged){var n={};if(typeof jQuery!=="undefined"&&typeof jQuery.ui!==
"undefined"&&typeof jQuery.ui.jig!=="undefined"&&typeof jQuery.ui.jig.scanned!=="undefined")if(jQuery.ui.jig.scanned){n=c();n.jsevent="domready";ncbi.sg.isScrollingEnabled&&e(n);ncbi.sg._ping(n);a._readyPinged=true}else{if(typeof jQuery.ui.jig.scan!=="undefined"&&jQuery.ui.jig.scan){var m=jQuery.ui.jig.scan;jQuery.ui.jig.scan=function(){var u=m.apply(this,arguments);g();return u}}}else{n.jigVersion="nojig";n.jsevent="domready";ncbi.sg.isScrollingEnabled&&e(n);ncbi.sg._ping(n);a._readyPinged=true}}};
if(document.addEventListener){var i=function(){document.removeEventListener("DOMContentLoaded",i,false);g()};document.addEventListener("DOMContentLoaded",i)}else if(document.attachEvent){var p=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",p);g()}};document.attachEvent("onreadystatechange",p)}},_setScrollingEnabled:function(){try{ncbi.sg.isScrollingEnabled=false;var a=ncbi.sgAppsWithScrolling;if(typeof a!=="undefined")for(var b=0;b<a.length;b++){var c=true,
e=a[b];for(var g in e)if(!this._cachedVals[g]||this._cachedVals[g].value.toLowerCase()!=e[g]){c=false;break}if(c){ncbi.sg.isScrollingEnabled=true;break}}}catch(i){ncbi.sg.getInstance().noteEventData("jserror",{jserror:i.toString(),SELF_URL:window.location.href},["ncbi_sessionid","ncbi_phid"])}},_setUpMetaTagValues:function(){for(var a=document.getElementsByTagName("meta"),b=0;b<a.length;b++){var c=a[b].name;c.indexOf("ncbi_")===0&&this.addEntry(c,a[b].content)}},_setUpCachedMetaTagValues:function(a){for(var b=
0;b<a.length;b++){var c=this._cachedVals[a[b]];c&&this.addEntry(a[b],c.value)}},cachedNames:["ncbi_app","ncbi_db","ncbi_pcid","ncbi_pdid","ncbi_phid","ncbi_sessionid","ncbi_uidlist"],ignoreLengthRestrictions:["jserror","jserrorlocation"],addEntry:function(a,b){if(!(b===undefined||b.length===0)){if(b.length>100&&this.ignoreLengthRestrictions.indexOf(a)===-1)b=b.substr(0,100);this._cachedVals[a]={sProp:a,value:b}}},getVal:function(a){return typeof this._cachedVals[a]!=="undefined"&&this._cachedVals[a]&&
typeof this._cachedVals[a].value!=="undefined"?this._cachedVals[a].value:null},removeAllEntries:function(){for(var a={},b=this.cachedNames.length,c=0;c<b;c++){var e=this.cachedNames[c],g=this._cachedVals[e];if(g)a[e]=g}this._cachedVals=a;for(var i in this._pathParts)this._pathParts[i]=""},_setUpCustomProps:function(){var a=this._pathParts.part1,b=this._pathParts.part2.length>0?":"+this._pathParts.part2:"",c=this._pathParts.part3.length>0?":"+this._pathParts.part3:"",e=this._pathParts.part4.length>
0?":"+this._pathParts.part4:"";a={pagename:a+b+c,server:window.location.hostname,sitesect2:a+b,subsect3:a+b+c,subsect4:a+b+c+e,heir1:(a+b+c+e).replace(/:/g,"|")};for(var g in a)this.addEntry(g,a[g]);this._sessionIdCheck();this._staticPageCheck();this._prevHitCheck();this._browserConfigurationSettings();this._hashCheck()},_staticPageCheck:function(){this._cachedVals.ncbi_app&&this._cachedVals.ncbi_app.value.length>0||this.addEntry("ncbi_app","static");this._cachedVals.ncbi_pdid&&this._cachedVals.ncbi_pdid.value.length>
0||this.addEntry("ncbi_pdid",(document.title||"unknown").replace(/\s+/g,""))},_sessionIdCheck:function(){if(!(this._cachedVals.ncbi_sessionid&&this._cachedVals.ncbi_sessionid.value.length>0)){var a="";if(a.length===0){var b=this.getCookie("ncbi_sid");if(b.length>0)a=b}if(a.length===0){b=this.getCookie("WebCubbyUser")||this.getCookie("WebEnv");if(b.length>0){b=unescape(b).split("@");if(b.length>1)a=b[b.length-1]}}if(a.length===0)a="UNK_SESSION";this.addEntry("ncbi_sessionid",a)}},getBrowserWidthHeight:function(){var a=
this.getViewportWidth(),b=this.getViewportHeight();return{width:a,height:b}},_browserConfigurationSettings:function(){if(ncbi.sg.calcXY){var a=this.getBrowserWidthHeight();this.addEntry("browserwidth",a.width);this.addEntry("browserheight",a.height);this.addEntry("screenwidth",screen.width);this.addEntry("screenheight",screen.height);this.addEntry("screenavailwidth",screen.availWidth);this.addEntry("screenavailheight",screen.availHeight);if(document&&document.body){var b=document.body.scrollWidth,
c=document.body.scrollHeight,e=c>a.height?"true":"false";this.addEntry("canscroll_x",b>a.width?"true":"false");this.addEntry("canscroll_y",e);this.addEntry("scrollwidth",b);this.addEntry("scrollheight",c)}}if(screen.colorDepth)this.addEntry("colorDepth",screen.colorDepth);else screen.pixelDepth&&this.addEntry("colorDepth",screen.pixelDepth)},_hashCheck:function(){var a=window.location.hash;if(a){a=a.replace("#","");this.addEntry("urlhash",a)}(a=window.location.search.match(/[?&]campaign=([^&]*)/))&&
this.addEntry("campaign",a[1])},_createPHID:function(){var a=this._cachedVals.ncbi_sessionid.value,b=a.substr(0,15)+"9"+(new Date).getTime().toString(),c=a.length;b+=a.substr(c-(32-b.length),c);a={value:b};this.addEntry("ncbi_phid",b);return a},currentPageHitId:null,_prevHitCheck:function(){var a=this.getCookie("ncbi_prevPHID"),b=this._cachedVals.ncbi_phid;a.length>0&&this.addEntry("prev_phid",a);if(!b||!b.value||b.value.length===0)b=this._createPHID();this.currentPageHitId=b.value;var c=this;ncbi.sg._hasFocus&&
c.setCookie("ncbi_prevPHID",b.value);var e=window.onfocus;window.onfocus=function(g){c.getCookie("ncbi_prevPHID")!==b.value&&c.setCookie("ncbi_prevPHID",b.value);typeof e==="function"&&e(g)}},_setUpPathParts:function(){var a=this._cachedVals.ncbi_app,b=this._cachedVals.ncbi_db,c=this._cachedVals.ncbi_pdid,e=this._cachedVals.ncbi_pcid;this._pathParts.part1=a!==undefined?a.value:"";this._pathParts.part2=b!==undefined?b.value:"";this._pathParts.part3=c!==undefined?c.value:"";this._pathParts.part4=e!==
undefined?e.value:""},getPerfStats:function(){var a=window.performance;if(!a)return{};var b=a.timing;if(b)b={dns:b.domainLookupEnd-b.domainLookupStart,connect:b.connectEnd-b.connectStart,ttfb:b.responseStart-b.connectEnd,basePage:b.responseEnd-b.responseStart,frontEnd:b.loadEventStart-b.responseEnd};else return{};if(a=a.navigation){b.navType=a.type;b.redirectCount=a.redirectCount}return b},setPerfStats:function(a,b){var c=this.getPerfStats();for(var e in c){var g=c[e];if(g>=0){var i="jsperf_"+e;if(b)a[i]=
g;else a.push(i+"="+g)}}},getExtraRenderStats:function(){var a={SELF_URL:encodeURIComponent(window.location.href)};if(typeof document!=="undefined"&&typeof document.referrer!=="undefined")a.HTTP_REFERER=encodeURIComponent(document.referrer);return a},setExtraRenderStats:function(a){var b=this.getExtraRenderStats();for(var c in b)a.push(c+"="+b[c])},_send:function(a,b,c){if(typeof c==="undefined"||c===null)c=true;var e=[];if(a==="init"){e.push("jsevent=render");ncbi.sg.renderTime=new Date;if(typeof ncbi_startTime!==
"undefined"){e.push("jsrendertime="+(ncbi.sg.renderTime-ncbi_startTime));ncbi.sg.loadTime&&e.push("jsloadtime="+(ncbi.sg.loadTime-ncbi_startTime))}this.setPerfStats(e);this.setExtraRenderStats(e);e.push("cookieenabled="+(ncbi.sg.isCookieEnabled?"true":"false"))}for(var g in this._cachedVals)ncbi.sg.appLogIgnore.indexOf(g)===-1&&e.push(g+"="+encodeURIComponent(this._cachedVals[g].value));this._sendAl(e.join("&"),b,true,c);this._hasInitRun=true;var i=this;setTimeout(function(){i.isProcessRunning=false;
i.runSGProcess()},300)},send:function(a,b){this._send(a,b,false)},_sendPrev:function(){var a=ncbi.sg.getInstance(),b;b=a.getCookie("prevselfurl")!=document.referrer?"false":"true";var c=a.getCookie("clicknext");if(c){c=ncbi.sg._urls.addAttrToStr("directnav",b,c);ncbi.sg._ping(c);a.setCookie("clicknext","")}if(c=a.getCookie("prevsearch")){c=ncbi.sg._urls.addAttrToStr("directnav",b,c);ncbi.sg._ping(c);a.setCookie("prevsearch","")}if(c=a.getCookie("unloadnext")){c=ncbi.sg._urls.addAttrToStr("directnav",
b,c);ncbi.sg._ping(c);a.setCookie("unloadnext","")}a.setCookie("prevselfurl","")},_sendAl:function(a,b,c,e){if(typeof e==="undefined"||e===null)e=true;var g=F(a);g=H(g,a);if(a.indexOf("jseventms")===-1)a+="&jseventms="+ncbi.sg.getInstance().getMillisecondsSinceSunday();if(a.match(/jsevent=search/i)){for(var i=ncbi.sg.addTimeonpageToAr([]),p=0;p<i.length;p++)a+="&"+i[p];a+="&eventid="+ncbi.sg.getEventId();i=a.replace(/jsevent=search(next)?/i,"jsevent=searchnext");this.setCookie("prevselfurl",window.location.href,
null);this._storeNext("prevsearch",i,null,e)}a+="&sgVersion="+ncbi.sg._version;if(a.indexOf("sgSource")===-1)a=this._setSgSource(a,e);a=ncbi.sg._urls.addDataToStr(g,a);e=window.location.port?":"+window.location.port:"";reqURL=typeof __ncbi_stat_url!=="undefined"?__ncbi_stat_url+"?"+a:window.location.protocol+"//"+window.location.hostname+e+"/stat?"+a;this.makeRequest(reqURL,function(){typeof b==="function"&&b()},c)},makeRequest:function(a,b,c){typeof ncbi_pingWithImage!=="undefined"&&ncbi_pingWithImage?
this.makeImgRequest(reqURL,function(){typeof callbackFnc==="function"&&callbackFnc()},c):this.makeAjaxCall(reqURL,function(){typeof callbackFnc==="function"&&callbackFnc()},c);this._pushPingFired(a)},sendAl:function(a,b,c){this._sendAl(a,b,c,false)},_processingQueue:[],isProcessRunning:false,addSGProcess:function(a){this._processingQueue.push(a)},getSGProcess:function(a){return this._processingQueue.shift(a)},runSGProcess:function(){if(this.isProcessRunning||this._processingQueue.length===0||!this._hasInitRun)return false;
this.isProcessRunning=true;this.removeAllEntries();var a=this.getSGProcess();this._setUpCachedMetaTagValues(a.metadata);this.addEntry("jsevent",a.eventName);for(var b in a.props)this.addEntry(b,a.props[b]);this._send(a.eventName,a.callbackFnc);var c=this;setTimeout(function(){c.isProcessRunning=false;c.runSGProcess()},300)},noteEventData:function(a,b,c,e){this.addSGProcess({eventName:a,props:b,metadata:c,callback:e});this.runSGProcess()},setCookie:function(a,b,c){if(window.sessionStorage)try{sessionStorage.setItem(a,
b)}catch(e){}var g=new Date;c!==null&&g.setDate(g.getDate()+c);document.cookie=a+"="+escape(b)+(c===null?"":"; expires="+g.toGMTString())+"; domain="+escape(".ncbi.nlm.nih.gov")+"; path=/"},_setSgSource:function(a,b){a+="&sgSource="+(b?"native":"api");return a},_storeNext:function(a,b,c,e){if(typeof e==="undefined"||e===null)e=true;b=this._setSgSource(b,e);this.setCookie(a,b,c)},getCookie:function(a){var b;if(window.sessionStorage){try{b=sessionStorage.getItem(a)||""}catch(c){b=""}if(b.length>0)return b}if(document.cookie.length>
0){b=document.cookie.indexOf(a+"=");if(b!==-1){b=b+a.length+1;a=document.cookie.indexOf(";",b);if(a===-1)a=document.cookie.length;return unescape(document.cookie.substring(b,a))}}return""},getTransport:function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest;this.getTransport=function(){return new XMLHttpRequest}}catch(b){a=null}if(window.ActiveXObject&&a===null)try{a=new ActiveXObject("Msxml2.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(c){try{a=
new ActiveXObject("Microsoft.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(e){a=false}}if(a===null)this.getTransport=function(){return null};return this.getTransport()},_shouldStorePing:function(a){return a.search(/jsevent=(click|search|unload)next/)!==-1||(a.search("jsevent=render")!==-1||a.search("jsevent=domready")!==-1||a.search("jsevent=jserror")!==-1)&&a.search("sgSource=api")===-1},_pushPingFired:function(a){this._shouldStorePing(a)&&ncbi.sg.pingsFired.push(a)},
_pushPingSucceeded:function(a){this._shouldStorePing(a)&&ncbi.sg.pingsSucceeded.push(a)},makeAjaxCall:function(a,b,c){var e=this,g=this.getTransport();g._ncbi_skipOverride=true;g.open("GET",a,c);if(c)g.onreadystatechange=function(){if(g.readyState===4){ncbi.sg.outstandingPings-=1;e._pushPingSucceeded(a);b(g)}};ncbi.sg.lastPing=g;ncbi.sg.outstandingPings+=1;g.send(null);return g},makeImgRequest:function(a,b){var c=this,e=document.createElement("img");e.setAttribute("src",a);e.style.display="none";
e.onload=function(){if(!this.complete||typeof this.naturalWidth==="undefined"||this.naturalWidth==0)console.warn("could not load stat img");else{c._pushPingSucceeded(a);b()}ncbi.sg.outstandingPings-=1;document.body.removeChild(e)};ncbi.sg.outstandingPings+=1;document.body.appendChild(e)},scrollDetails:{maxScroll_x:0,maxScroll_y:0,currScroll_x:0,currScroll_y:0,hasScrolled:false},scrollEventDetails:{xTenths:0,yTenths:0,xMax:0,yMax:0},_visibleHeadings:[],_hiddenHeadings:[],_getScrollXYPx:function(){return[window.pageXOffset||
document.documentElement.scrollLeft||document.body.scrollLeft||0,window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0]},_getScrollXY:function(){var a=this.getViewportHeight(),b=this.getViewportWidth(),c=document.body.scrollHeight,e=document.body.scrollWidth,g=this._getScrollXYPx(),i=Math.round(g[1]/a*10)/10;return{xRel:Math.round(g[0]/b*10)/10,yRel:i,viewportHeight:a,viewportWidth:b,pageHeight:c,pageWidth:e}},_addOnScrollListeners:function(){var a=window.onscroll,b=this;
window.onscroll=function(){if(ncbi.sg.isScrollingEnabled){b._setScrollDetails();b.scrollDetails.hasScrolled=true;b._addScrollEvent()}else{b._setScrollDetails();b.scrollDetails.hasScrolled=true}if(typeof a==="function")return a()}},getViewportHeight:function(){return window.innerHeight?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body!==null?document.body.clientHeight:"NA"},getViewportWidth:function(){return window.innerWidth?
window.innerWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:document.body!==null?document.body.clientWidth:"NA"},_setScrollDetails:function(){if(ncbi.sg.calcXY){this.scrollDetails.currScroll_y=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;this.scrollDetails.currScroll_x=window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft||0;this.getViewportWidth();this.getViewportHeight();if(this.scrollDetails.maxScroll_y<
this.scrollDetails.currScroll_y)this.scrollDetails.maxScroll_y=this.scrollDetails.currScroll_y;if(this.scrollDetails.maxScroll_x<this.scrollDetails.currScroll_x)this.scrollDetails.maxScroll_x=this.scrollDetails.currScroll_x}},isVisible:function(a){var b=this.findEffectiveStyleProperty(a,"visibility");a=this._isDisplayed(a);return b!="hidden"&&a},_isDisplayed:function(a){if(this.findEffectiveStyleProperty(a,"display")=="none")return false;if(a.parentNode.style)return this._isDisplayed(a.parentNode);
return true},findEffectiveStyleProperty:function(a,b){var c=this.findEffectiveStyle(a)[b];if(c=="inherit"&&a.parentNode.style)return this.findEffectiveStyleProperty(a.parentNode,b);return c},findEffectiveStyle:function(a){if(a.style!=undefined){if(window.getComputedStyle)return window.getComputedStyle(a,null);if(a.currentStyle)return a.currentStyle;if(window.document.defaultView&&window.document.defaultView.getComputedStyle)return window.document.defaultView.getComputedStyle(a,null);return null}},
findElementPos:function(a,b,c){var e=0,g=0;if(a.offsetLeft)e+=parseInt(a.offsetLeft);if(a.offsetTop)g+=parseInt(a.offsetTop);if(a.scrollTop&&a.scrollTop>0){g-=parseInt(a.scrollTop);c=true}if(a.scrollLeft&&a.scrollLeft>0){e-=parseInt(a.scrollLeft);b=true}if(a.offsetParent){b=this.findElementPos(a.offsetParent,b,c);if(b==-1)return-1;e+=b[0];g+=b[1]}else if(a.ownerDocument){var i=a.ownerDocument.defaultView;if(!i&&a.ownerDocument.parentWindow)i=a.ownerDocument.parentWindow;if(i){var p=i.pageXOffset!==
undefined?i.pageXOffset:(a.document.documentElement||a.document.body.parentNode||a.document.body).scrollLeft;a=i.pageYOffset!==undefined?i.pageYOffset:(a.document.documentElement||a.document.body.parentNode||a.document.body).scrollTop;if(!c&&a&&a>0)g-=parseInt(a);if(!b&&p&&p>0)e-=parseInt(p)}}return[e,g]},getJoinedData:function(a){var b=[];for(var c in a)b.push(c+"="+encodeURIComponent(a[c]));return b.join("&")},addScrollHeadingData:function(a,b){var c=this.scrollEventDetails.headings;if(c){a["numHeadings."+
this._scrollOrder+".scrollInfo"]=c.length;for(var e=0;e<c.length;e++){var g=c[e];if(g.visible){var i={};if(g.innerText)i["innerText."+g.index+".headings."+this._scrollOrder+".scrollInfo"]=g.innerText;if(g.id)i["id."+g.index+".headings."+this._scrollOrder+".scrollInfo"]=g.id;i["tagName."+g.index+".headings."+this._scrollOrder+".scrollInfo"]=g.tagName;b=b?b:1800;this.getJoinedData(a).length+this.getJoinedData(i).length<b&&ncbi.sg._urls.addDataToObj(a,i)}}}return a},storeAllHeadings:function(){for(var a=
[],b=[],c=document.getElementsByTagName("*"),e=-1,g=0;g<c.length;g++){for(var i=c[g],p=false,n=i.tagName.toLowerCase(),m=0;m<7;m++)if(n=="h"+m)p=true;if(p){e+=1;m=this.findElementPos(i);p=m[1];m=m[0];var u=i.offsetHeight,z=i.offsetWidth,w=this.getViewportHeight(),d=this.getViewportWidth(),f={},h=i.getAttribute("id")||i.id;if(h)f.id=h;if(h=(i.getAttribute("innerText")||i.innerText||i.getAttribute("textContent")||i.textContent||"").replace(/^\s+|\s+$/g,""))f.innerText=h.substring(0,50);f.index=e;f.tagName=
n;n=false;if(p+u>=0&&p<=w&&m+z>=0&&m<=d)if(this.isVisible(i))n=true;(f.visible=n)?a.push(f):b.push(f)}}this._visibleHeadings=a;this._hiddenHeadings=b},getVisibleHeadings:function(){return this._visibleHeadings},getHiddenHeadings:function(){return this._hiddenHeadings},getVisibleHeadingIDs:function(){for(var a=this.getVisibleHeadings(),b=[],c=0;c<a.length;c++)b.push(a[c].id);return b},getHiddenHeadingIDs:function(){for(var a=this.getHiddenHeadings(),b=[],c=0;c<a.length;c++)b.push(a[c].id);return b},
_setBeforeScrollDetails:function(a){this._lastScroll=a?a:null;if(ncbi.sg.calcXY){a=this._getScrollXY();var b=a.yRel;this.scrollEventDetails.xTenths=Math.round(a.xRel*10);this.scrollEventDetails.yTenths=Math.round(b*10);this.scrollEventDetails.xMax=Math.max(this.scrollEventDetails.xTenths,this.scrollEventDetails.xMax);this.scrollEventDetails.yMax=Math.max(this.scrollEventDetails.yTenths,this.scrollEventDetails.yMax)}this.storeAllHeadings();this.scrollEventDetails.headings=this.getVisibleHeadings()},
getScrollDetails:function(a,b){if(!ncbi.sg.isScrollingEnabled)if(ncbi.sg.calcXY){this._setScrollDetails();return this.scrollDetails}else return{};var c=this.scrollEventDetails;c.tstamp=(new Date).getTime();var e=this._getScrollXY(),g=null;if(b||!this._lastScroll||c.tstamp-this._lastScroll>1E3){this._scrollOrder=this._scrollOrder!=undefined?this._scrollOrder+1:0;if(ncbi.sg.calcXY)var i="yTenths."+this._scrollOrder+".scrollInfo",p="xTenths."+this._scrollOrder+".scrollInfo",n="maxXTenths."+this._scrollOrder+
".scrollInfo",m="maxYTenths."+this._scrollOrder+".scrollInfo";b={};b["duration."+this._scrollOrder+".scrollInfo"]=this._lastScroll?c.tstamp-this._lastScroll:new Date-ncbi.sg.loadTime;if(ncbi.sg.calcXY){b[p]=this.scrollEventDetails.xTenths;b[i]=this.scrollEventDetails.yTenths;b[n]=this.scrollEventDetails.xMax;b[m]=this.scrollEventDetails.yMax;b["viewportHeight."+this._scrollOrder+".scrollInfo"]=e.viewportHeight;b["viewportWidth."+this._scrollOrder+".scrollInfo"]=e.viewportWidth;b["maxPossibleScrollTenthsY."+
this._scrollOrder+".scrollInfo"]=Math.round((e.pageHeight/e.viewportHeight-1)*10);b["maxPossibleScrollTenthsX."+this._scrollOrder+".scrollInfo"]=Math.round((e.pageWidth/e.viewportWidth-1)*10)}g=b=this.addScrollHeadingData(b,a)}this._setBeforeScrollDetails(c.tstamp);return g},getScrollDetailsAr:function(a,b){var c=[];a=this.getScrollDetails(a,b);for(var e in a)c.push(e+"="+encodeURIComponent(a[e]));return c},addScrollDetailsAr:function(a,b,c){b=this.getScrollDetailsAr(b,c);for(c=0;c<b.length;c++)a.push(b[c])},
addScrollDetails:function(a,b,c){b=this.getScrollDetails(b,c);for(var e in b)a[e]=b[e]},_addScrollEvent:function(){try{var a=this.getScrollDetails();if(a){a.jsevent="scroll";ncbi.sg._ping(a)}}catch(b){ncbi.sg.getInstance().noteEventData("jserror",{jserror:b.toString(),SELF_URL:window.location.href},["ncbi_sessionid","ncbi_phid"])}},_addPrintPing:function(){function a(){var e=document.createElement("style");e.type="text/css";var g=document.createElement("style");g.type="text/css";g.media="print";for(var i=
["jsevent=print"],p=0;p<b.cachedNames.length;p++){var n=b.cachedNames[p],m=b._cachedVals[n];m&&n!=="ncbi_sessionid"&&i.push(n+"="+encodeURIComponent(m.value))}i=".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }.print-log li { list-style-image: url('/stat?"+i.join("&")+"'); }";if(g.styleSheet){g.styleSheet.cssText=i;e.styleSheet.cssText=".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"}else{g.appendChild(document.createTextNode(i));
e.appendChild(document.createTextNode(".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"))}i=document.getElementsByTagName("head")[0];i.appendChild(g);i.appendChild(e);e=document.createElement("ul");e.className="print-log";g=document.createElement("li");e.appendChild(g);document.body.appendChild(e)}var b=this;if(typeof jQuery!=="undefined")jQuery(a);else{var c=window.onload;window.onload=function(e){c&&c(e);a()}}},getMillisecondsSinceSunday:function(){var a=
new Date,b=new Date;b.setDate(b.getDate()-b.getDay());b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);return(a-b).toString(36)},addLinkObjs:function(a){this._linkObjs.push(a)},isInLinkObjs:function(a){for(var b=this._linkObjs,c=0;c<b.length;c++)for(var e=b[c],g=0;g<e.length;g++)if(a==e[g])return true;return false}};ncbi.sg.lastPing=null;ncbi.sg.hasNotedErrorEvent=false;ncbi.sg.getTimeonpageData=function(){var a={};if(typeof ncbi_startTime!=="undefined"){a.ncbi_timeonpage=new Date-
ncbi_startTime;if(typeof ncbi_onloadTime!=="undefined"&&ncbi_onloadTime)a.ncbi_onloadTime=ncbi_onloadTime-ncbi_startTime}return a};ncbi.sg.addTimeonpageDetails=function(a){var b=ncbi.sg.getTimeonpageData();for(var c in b)a[c]=b[c];return a};ncbi.sg.addTimeonpageToAr=function(a){var b=ncbi.sg.getTimeonpageData();for(var c in b)a.push(c+"="+b[c]);return a};(function(){function a(){ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);if(m.length>0)for(;m.length>0;)c(m.pop());
var d={jsevent:"unload",ncbi_pingaction:"unload"};d=ncbi.sg.addTimeonpageDetails(d);d.eventid=ncbi.sg.getEventId();var f=ncbi.sg.getInstance();f.setPerfStats(d,true);f.addScrollDetails(d,1800-f.getJoinedData(d).length,true);if(!w){ncbi.sg._ping(d);var h="";for(var k in d)h+=k+"="+(k==="jsevent"?"unloadnext":d[k])+"&";h+="ncbi_phid="+f.currentPageHitId;f.setCookie("prevselfurl",window.location.href,null);f._storeNext("unloadnext",h,null)}w=true}function b(d){for(var f=m.length-1;f>=-1;f--)if(m[f]===
d){m.slice(f,1);break}c(d)}function c(d,f){if(u.indexOf(d.tstamp)===-1){u.push(d.tstamp);z.push(d);e("click",d,f)}}function e(d,f,h,k){if(typeof k==="undefined"||k===null)k=true;var o=d==="click"?"link":"elem",l=f.link,s=f.evt,j=l.id||"",q=l.name||"",v=l.sid||"",y=l.href||"",A=l.innerText||l.textContent||"";if(A.length>50)A=A.substr(0,50);var D=l.getAttribute?l.getAttribute("ref")||l.ref||"":"",E=l.className?l.className.replace(/^\s?/,"").replace(/\s?$/,"").split(/\s/g).join(",")||"":"";f=[];var B=
[],x=l.parentNode;if(x)for(var t=0;t<6&&x!==null;t++){(parId=x.id)&&f.push(parId);if(parClassName=x.className)B=B.concat(parClassName.split(/\s/));x=x.parentNode}x=ncbi.sg.getInstance();t=x.currentPageHitId||"";var r=[];j.length>0&&r.push(o+"_id="+encodeURIComponent(j));q.length>0&&r.push(o+"_name="+encodeURIComponent(q));v.length>0&&r.push(o+"_sid="+encodeURIComponent(v));y.length>0&&r.push(o+"_href="+encodeURIComponent(y));A.length>0&&r.push(o+"_text="+encodeURIComponent(A));E.length>0&&r.push(o+
"_class="+encodeURIComponent(E));if(ncbi.sg.calcXY){t=x.getBrowserWidthHeight();t.width!==null&&r.push("browserwidth="+encodeURIComponent(t.width));t.height!==null&&r.push("browserheight="+encodeURIComponent(t.height))}for(var C in s){t=s[C];t!==undefined&&r.push(C.toLowerCase()+"="+t.toString())}d==="click"&&r.push("eventid="+encodeURIComponent(ncbi.sg.getEventId()));r.push("jsevent="+d);D.length>0&&r.push(D);if(typeof jQuery!=="undefined")if(l=jQuery(l).attr("sg")){l=l.split(/\}\s*,\s*\{/);for(t=
0;t<l.length;t++){s=l[t].match(/name\s*:\s*'(.+)',\s*selector\s*:\s*'(.+)'/);if(s.length===3){C="cust_"+s[1];s=jQuery(s[2]).val();r.push(C+"="+encodeURIComponent(s))}}}if(h&&h.length>0)for(;h.length>0;)r.push(h.shift());f.length>0&&r.push("ancestorId="+f.join(","));B.length>0&&r.push("ancestorClassName="+B.join(",").replace(/\s+/g," ").replace(/(^\s|\s$)/g,""));x.addScrollDetailsAr(r,1800-r.join("&").length,true);if(d==="click"){r=ncbi.sg.addTimeonpageToAr(r);d=r.join("&").replace("jsevent=click",
"jsevent=clicknext");t=ncbi.sg.getInstance().currentPageHitId||"";d+="&ncbi_phid="+t;x.setCookie("prevselfurl",window.location.href,null);x._storeNext("clicknext",d,null,k)}ncbi.sg._ping(r,true,null,null,k)}function g(d){var f={};if(ncbi.sg.calcXY&&d){if(d.clientX||d.clientY){var h=ncbi.sg.getInstance()._getScrollXYPx();f.evt_coor_x=d.clientX+h[0];f.evt_coor_y=d.clientY+h[1]}else if(d.pageX||d.pageY){f.evt_coor_x=d.pageX;f.evt_coor_y=d.pageY}f.jseventms=ncbi.sg.getInstance().getMillisecondsSinceSunday()}return f}
function i(d,f,h,k,o){var l={},s=null,j=null;if(typeof f==="string"){s=f;j=h}else{l=g(f);s=h;j=k}if(j){f=typeof j;if(f==="string")j=[j];else if(f==="object"&&!(j instanceof Array)){f=[];for(var q in j)f.push(q+"="+j[q]);j=f}}e(s,{link:d,evt:l},j,o)}function p(d,f,h){var k=[];if(typeof f==="undefined")f=true;if(typeof d==="object"&&!(d instanceof Array))for(var o in d)k.push(o+"="+encodeURIComponent(d[o]));else if(typeof d==="string")k.push(d);else k=d;d=ncbi.sg.getInstance().currentPageHitId||"";
o=null;if(typeof ncbi.sg.loadTime!=="undefined")o=new Date-ncbi.sg.loadTime;var l=k.join("&");if(l.indexOf("jsevent=clicknext")!==-1||l.indexOf("jsevent=searchnext")!==-1||l.indexOf("jsevent=unloadnext")!==-1){d.length>0&&k.push("next_phid="+encodeURIComponent(d));o!==null&&k.push("next_ncbi_timesinceload="+o)}else{d.length>0&&k.push("ncbi_phid="+encodeURIComponent(d));o!==null&&k.push("ncbi_timesinceload="+o)}ncbi.sg.getInstance()._sendAl(k.join("&"),null,f,h)}var n=window.onerror;window.onerror=
function(d,f,h){if(!ncbi.sg.hasNotedErrorEvent){ncbi.sg.getInstance().noteEventData("jserror",{jserror:d,jserrorlocation:f,jserrorline:h,SELF_URL:window.location.href},["ncbi_sessionid","ncbi_phid"]);ncbi.sg.hasNotedErrorEvent=true;if(typeof n==="function")return n(d,f,h)}};ncbi.sg._currentEventId=1;ncbi.sg.getEventId=function(){return ncbi.sg._currentEventId++};var m=[],u=[],z=[],w=false;ncbi.sg.sendElementEvent=function(d,f,h){e(d,f,h,false)};ncbi.sg.clickTimers=[];setClickEvent=function(){function d(){a()}
var f=function(j){return(j=typeof j.parentNode!=="undefined"?j.parentNode:null)?o(j)?j:f(j):false},h=function(j){var q=j.target||j.srcElement;if(typeof q=="undefined"||q==null)return null;if(q.nodeType==3)q=j.target.parentNode;o(q)||(q=f(q));return q},k=function(j){return ncbi.sg.getInstance().isInLinkObjs(j)},o=function(j){var q=typeof j.tagName!=="undefined"?j.tagName.toLowerCase():null,v=false,y=false;if(typeof jQuery!=="undefined")v=jQuery(j).is("button, input[type=button], input[type=submit], input[type=reset]");
else if(q==="input"){v=j.type;v=v=="button"||v=="submit"||v=="reset"}else v=q==="button"?true:false;v||(y=q=="a"||q=="area");return y?"link":v?"button":k(j)?"linkObjs":null},l=function(j,q,v,y){if(!(y&&y=="click"&&j.which&&j.which==3))if(!(!q||o(q)==null)){ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);j=g(j);j.iscontextmenu=y=="contextmenu"?"true":"false";q={evt:j,link:q,tstamp:(new Date).getTime(),floodTstamp:(new Date).getTime()};b(q);ncbi.sg.clickTimers&&
window.clearTimeout(ncbi.sg.clickTimers);ncbi.sg.clickTimers=window.setTimeout(function(){ncbi.sg.clickTimers=null},300)}};if(window.addEventListener){window.addEventListener("click",function(j){l(j,h(j),[],"click")});window.addEventListener("contextmenu",function(j){l(j,h(j),[],"contextmenu")},false);window.addEventListener("beforeunload",d)}else if(window.attachEvent){document.attachEvent("onclick",function(j){l(j,h(j),[],"click")});document.attachEvent("oncontextmenu",function(j){l(j,h(j),[],"contextmenu")},
false);document.attachEvent("onbeforeunload",d)}if(Event.prototype.stopPropagation){var s=Event.prototype.stopPropagation;Event.prototype.stopPropagation=function(){var j=h(this);if(o(j)!=null)if(this.type=="click")l(this,j,[],"click");else this.type=="contextmenu"&&l(this,j,[],"contextmenu");return s.apply(this,arguments)}}};ncbi.sg.isClickingEnabled&&setClickEvent();ncbi.sg.scanLinks=function(d){var f=ncbi.sg.getInstance();if(d){var h=typeof jQuery!=="undefined"&&jQuery?d instanceof jQuery:false;
if(typeof d==="object"&&!(d instanceof Array)&&!h)d=[d];f.addLinkObjs(d)}};ncbi.sg._ping=function(d,f,h,k,o){if(typeof o==="undefined"||o===null)o=true;typeof d==="undefined"||d===null||(typeof d==="object"&&d.nodeName!==undefined?i(d,f,h,k,o):p(d,f,o))};ncbi.sg.ping=function(d,f,h,k){ncbi.sg._ping(d,f,h,k,false)};ncbi.sg.loadTime=new Date;ncbi.sg.pingsFired=[];ncbi.sg.pingsSucceeded=[];ncbi.sg.prevPingsFired=null;ncbi.sg.prevPingsSucceeded=null;ncbi.sg.outstandingPings=0;ncbi.sg._isGBPage=false;
ncbi.sg._urls={getDataObj:function(d){if(typeof d==="string"||typeof DOMString!=="undefined"&&d instanceof DOMString||typeof String!=="undefined"&&d instanceof String){var f={};d=d.split("&");for(var h=0;h<d.length;h++)if(d[h].length){var k=d[h].split("="),o=k[0],l="";if(k.length==1)l="";else{l=k[1];if(k.length>2)for(var s=2;s<k.length;s++)l+="="+k[s]}f[o]=l}return f}else return false},getUrlParts:function(d){if(typeof d!=="undefined"&&d){d=d.split("?");if(d.length<=2)return d;else{for(var f=d[1],
h=2;h<d.length;h++)f+="?"+d[h];return[d[0],f]}}return""},getQueryString:function(d){d=this.getUrlParts(d);return d.length>1?typeof d[1]!=="undefined"&&d[1]?d[1]:"":null},getMainUrlPart:function(d){d=this.getUrlParts(d);return d.length>0?typeof d[0]!=="undefined"&&d[0]?d[0]:"":""},hasQuestionMark:function(d){return d.search(/\?/)!==-1},getDataStr:function(d){if(typeof d==="object"&&!(d instanceof Array)){var f=[];for(var h in d)f.push(h+"="+d[h]);return f.join("&")}else return false},attrInStr:function(d,
f){if(typeof f!=="undefined"&&f&&f.length>0)if(typeof this.getDataObj(f)[d]!=="undefined")return true;return false},attrInUrl:function(d,f){return this.attrInStr(this.getQueryString(f))},getAttrFromData:function(d,f){if(typeof f!=="undefined")return f[d]},getAttrFromStr:function(d,f){return this.getAttrFromData(d,this.getDataObj(f))},addAttr:function(d,f,h){h[d]=f;return h},addAttrToStr:function(d,f,h){h=this.getDataObj(h);h=this.addAttr(d,f,h);return this.getDataStr(h)},addDataToStr:function(d,f){f=
f;for(var h in d)f=this.addAttrToStr(h,d[h],f);return f},addDataToObj:function(d,f){for(var h in f)d[h]=f[h]},addAttrWithIndex:function(d,f,h){var k=ncbi.sg.getInstance();if(typeof d==="undefined"||!d)return f;if(typeof f!=="undefined"&&f){k=k.getVal(d);f[d]=k?k:"unknown";if(typeof h!=="undefined"&&h)f[d]+=".0"+ncbi.sg._ajaxRequestIndex}return f},addAttrWithIndexToUrl:function(d,f,h){var k=this.getMainUrlPart(f);f=this.getQueryString(f);f=f!==null?f:"";f=this.addAttrWithIndexToStr(d,f,h);return k+
"?"+f},addAttrWithIndexToStr:function(d,f,h){f=this.getDataObj(f);ncbi.sg.getInstance();f=this.addAttrWithIndex(d,f,h);return this.getDataStr(f)}}})();if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){var c=this.length>>>0;b=Number(b)||0;b=b<0?Math.ceil(b):Math.floor(b);if(b<0)b+=c;for(;b<c;b++)if(b in this&&this[b]===a)return b;return-1};(function(){function a(){ncbi_onloadTime=new Date}ncbi_onloadTime=null;if(typeof jQuery!=="undefined")jQuery(window).load(a);else{var b=window.onload;
window.onload=function(c){b&&b(c);a()}}})();(function(){ncbi.sg._ajaxRequestIndex=1;if(typeof XMLHttpRequest!=="undefined"){var a,b=function(e,g,i,p){if(typeof a==="undefined"||!a)a=ncbi.sg.getInstance();g=(g=a.getVal(g))?g:"unknown";if(typeof p!=="undefined"&&p)g+=".0"+ncbi.sg._ajaxRequestIndex;e.setRequestHeader(i,g)},c=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(){var e;if(typeof this._ncbi_skipOverride!=="undefined"&&this._ncbi_skipOverride)e=c.apply(this,arguments);else{e=
arguments&&arguments.length>1&&typeof arguments[1]!=="undefined"?arguments[1]:null;if(e!==null&&ncbi.sg._isGBPage){e=ncbi.sg._urls.addAttrWithIndexToUrl("ncbi_phid",e,true);e=ncbi.sg._urls.addAttrWithIndexToUrl("ncbi_sessionid",e);arguments[1]=e}e=c.apply(this,arguments);b(this,"ncbi_phid","NCBI-PHID",true);ncbi.sg._ajaxRequestIndex+=1}return e}}})()}})();

;
// This code creates window.console if it doesn't exist.
// It also creates stub functions for those functions that are missing in window.console.
// (Safari implements some but not all of the firebug window.console methods--this implements the rest.)
(function() {
    var names = [ "log", "debug", "info", "warn", "error", "assert", "dir", "dirxml", "group",
                  "groupEnd", "time", "timeEnd", "count", "trace", "profile", "profileEnd" ];

    if (typeof(console) === 'undefined' || typeof console === "function" ) {
      //"typeof function" is needed see PP-769 
      console = {};
    }

    for (var i = 0; i < names.length; ++i) {
       if (typeof(console[names[i]]) === 'undefined') {
          console[names[i]] = function() { return false; };
       }
    }
    ncbi.sg.getInstance().init();                          
})();
